# syntax = docker/dockerfile:1

# Stage 1: Dependencies
FROM public.ecr.aws/amazonlinux/amazonlinux:2023 AS deps

RUN dnf -y install nodejs22

WORKDIR /app

# Set production environment
ENV CI=true

# Copy package.json and package-lock.json
# to the /app working directory
COPY package*.json ./

# Install dependencies in /app (excluding devDependencies)
# RUN npm ci
RUN npm install

# Step 2: Builder
FROM public.ecr.aws/amazonlinux/amazonlinux:2023 AS builder

RUN dnf -y install nodejs22

WORKDIR /app

# Set production environment
ENV CI=true

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build the application
RUN npm run build

# Prune node_modules to only production-ready ones AFTER build
# RUN npm ci --omit=dev \
#     && npm cache clean --force \
#     # Verify jest/babel are gone before runner copies this
#     && ls node_modules | grep -v "jest\|babel\|typescript\|eslint" > /dev/null \
#     # We don't need the package files now that the code is compiled and it just messes
#     # up the Trivy scans
#     && rm package-lock.json && rm package.json

# Remove all test and mock files from the distribution
RUN rm -rf dist/__tests__ \
           dist/__mocks__ \
           dist/**/__tests__ \
           dist/**/__mocks__

# Stage 3: Runner
FROM public.ecr.aws/amazonlinux/amazonlinux:2023 AS runner

RUN rm -fr /var/cache/dnf/* && dnf clean all && dnf -y update && dnf -y install \
  nodejs22 \
  && dnf clean all

WORKDIR /app

# Only copy the compiled code and the pruned node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 4646

# Start the application
CMD ["node", "dist/server.js"]
